=== YosafatM/ESCOM/Web/Practicas/P2/cuestionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- editado con XMLSpy v2020 rel. 2 (x64) (http://www.altova.com) por Yosafat -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="RELACION_DE_COLUMNAS">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PREGUNTA" type="pregunta_type"/>
			</xs:sequence>
			
			<xs:attribute name="PLANTILLA" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="pregunta_type">
		<xs:sequence>
			<xs:element name="DRAGS" type="drag_and_target_type"/>
			<xs:element name="TARGETS" type="drag_and_target_type"/>
		</xs:sequence>
		
		<xs:attribute name="TEXTO" type="xs:string"/>
		<xs:attribute name="RESPUESTA" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="drag_and_target_type">
		<xs:sequence>
			<xs:element name="OPCION" type="opcion_type"/>
			<xs:element name="OPCION" type="opcion_type"/>
			<xs:element name="OPCION" type="opcion_type"/>
			<xs:element name="OPCION" type="opcion_type"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="opcion_type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="IMAGEN" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== YosafatM/ESCOM/Web/Practicas/P2/cuestionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<RELACION_DE_COLUMNAS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" PLANTILLA="prototipo_RC.swf" xsi:noNamespaceSchemaLocation="cuestionario.xsd">
	<PREGUNTA TEXTO="Relacione los presidentes mostrados abajo con su respectiva nacion" RESPUESTA="OP1-3;OP2-4;0P3-1;0P4-2">
		<DRAGS>
			<OPCION IMAGEN="presidente2.jpg">Fidel Castro</OPCION>
			<OPCION IMAGEN="presidente4.jpg">George W. Bush</OPCION>
			<OPCION IMAGEN="presidente3.jpg">Vicente Fox</OPCION>
			<OPCION IMAGEN="presidente1.jpg">Ricardo Lagos</OPCION>
		</DRAGS>
		<TARGETS>
			<OPCION IMAGEN="nacion3.jpg">Mexico</OPCION>
			<OPCION IMAGEN="nacion1.jpg">Chile</OPCION>
			<OPCION IMAGEN="nacion2.jpg">Cuba</OPCION>
			<OPCION IMAGEN="nacion4.jpg">Estados Unidos</OPCION>
		</TARGETS>
	</PREGUNTA>
</RELACION_DE_COLUMNAS>
